seed_everything : 3

model:
  loss_params:
    name : BCELossForET
  ET_Network_params:
    name : BaseEntityTypingNetwork
    network_params:
      encoder_params:
        name : AdapterDistilBERTEncoder
        bertlike_model_name: distilbert-base-uncased
        adapter_arch : Pfeiffer
        reduction_factor : 16
      type_encoder_params:
        name : OneHotTypeEncoder
        trainable: False
      input_projector_params:
        name : Classifier
        layers_parameters: 
          '0':
            in_features : encoder_dim
            out_features: in_features
            use_dropout: False
            activation: relu
          '1':
            in_features: previous_out_features
            out_features : type_number
            use_dropout: False
            activation: sigmoid
  inference_params:
    name: BaseInference
    threshold: 0.5

trainer:
  deterministic: True
  gpus: 1
  limit_train_batches: 160
  max_epochs : 100
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: trained_models_chronos_exp/bbn/
        monitor: val_loss
        filename: baseline_distilbert
        save_weights_only: True
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
        verbose: True

data:
  dataset_paths:
    train: datasets/bbn/train.json
    dev: datasets/bbn/dev.json
    test: datasets/bbn/test-12k.json
  # train_test_mapping:
  #   livingthing: living_thing
  dataset_reader_params:
    name : BaseDataset
  tokenizer_params:
    name : BaseBERTTokenizedDataset
    bertlike_model_name: distilbert-base-uncased
    max_mention_words: 5
    max_right_words: 13
    max_left_words: 13
    max_tokens: 80
  dataset_params:
    name: ET_Dataset
  dataloader_params:
    name: torch.DataLoader
    train:
      batch_size: 64
      shuffle: True
    dev:
      batch_size: 64
    test:
      batch_size: 64
  rw_options:
    modality: Load # in [Create, CreateAndSave, Load]
    dirpath: datasets/bbn/tokenized 
    light: True
  

logger:
  project : tmp
  entity : cbe
  name : bbn_baseline
  config_file: entity_typing_experiments/chronos_experiments/bbn_baseline.yaml