seed_everything : 1

model:
  loss_params:
    name : BoxEmbeddingBCELoss
  ET_Network_params:
    name : BoxEmbeddingEntityTypingNetwork
    network_params:
      encoder_params:
        name : DistilBERTEncoder
        bertlike_model_name: distilbert-base-uncased
        freeze_encoder : True
      box_embeddings_dimension: 109
      type_encoder_params:
        name : BoxDecoder
        inv_softplus_temp: 1.2471085395024732
        softplus_scale: 1.
        n_negatives: 1000
        box_offset: 0.5
        use_gumbel_baysian: True
        gumbel_beta: 0.00036026463511690845
      input_projector_params:
        name : BoxEmbeddingProjector
        projection_network_params:
          name: HighwayNetwork
          n_layers: 2
  inference_params:
    name: BoxEmbeddingInference

trainer:
  deterministic: True
  gpus: 1
  limit_train_batches: 160
  max_epochs : 100
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: trained_models_chronos_exp/bbn/
        monitor: val_loss
        filename: baseline_distilbert
        save_weights_only: True
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
        verbose: True

data:
  dataset_paths:
    train: datasets/ren_et_al/bbn/train.json
    dev: datasets/ren_et_al/bbn/dev.json
    test: datasets/ren_et_al/bbn/test-12k.json
  dataset_reader_params:
    name : BaseDataset
  tokenizer_params:
    name : BaseBERTTokenizedDataset
    bertlike_model_name: distilbert-base-uncased
    max_mention_words: 5
    max_right_words: 13
    max_left_words: 13
    max_tokens: 80
  dataset_params:
    name: ET_Dataset
  dataloader_params:
    name: torch.DataLoader
    train:
      batch_size: 64
      shuffle: True
    dev:
      batch_size: 64
    test:
      batch_size: 64
  rw_options:
    modality: Load # in [Create, CreateAndSave, Load]
    dirpath: datasets/bbn/tokenized 
    light: True
  

logger:
  project : entity_typing_framework
  entity : noonebug
  name : box_embedding_baseline_bbn
  config_file: entity_typing_framework/default_configurations/box_embeddings.yaml