seed_everything : 1

model:
  loss_params:
    name : BoxEmbeddingBCELoss
  ET_Network_params:
    name : BoxEmbeddingEntityTypingNetwork
    network_params:
      encoder_params:
        name : DistilBERTEncoder
        bertlike_model_name: distilbert-base-uncased
        freeze_encoder : True
      type_encoder_params:
        name : OneHotTypeEncoder
        trainable: False
      input_projector_params:
        name : BoxEmbeddingProjector
        box_embeddings_dimension: 109
        projection_network_params:
          name: HighwayNetwork
          n_layers: 2
        box_decoder_params:
          inv_softplus_temp: 1.2471085395024732
          softplus_scale: 1.
          n_negatives: 1000
          box_offset: 0.5
          use_gumbel_baysian: True
          gumbel_beta: 0.00036026463511690845
  inference_params:
    name: BoxEmbeddingInference

trainer:
  deterministic: True
  gpus: 1
  limit_train_batches: 10
  max_epochs : 2
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: cancellami/bbn/
        monitor: val_loss
        filename: trained_models_incremental_exp/figer/dummy_pretraining_box_location
        save_weights_only: True
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
        verbose: True

data:
  dataset_paths:
    train: ../datasets/datasets_for_incremental_training/figer/pretraining_location.json
    dev: ../datasets/datasets_for_incremental_training/figer/pretraining_location_dev.json
    test: ../datasets/datasets_for_incremental_training/figer/pretraining_location_test.json
  dataset_reader_params:
    name : BaseDataset
  tokenizer_params:
    name : BaseBERTTokenizedDataset
    bertlike_model_name: distilbert-base-uncased
    max_mention_words: 1
    max_right_words: 1
    max_left_words: 1
    max_tokens: 5
  dataset_params:
    name: ET_Dataset
  dataloader_params:
    name: torch.DataLoader
    train:
      batch_size: 64
      shuffle: True
    dev:
      batch_size: 64
    test:
      batch_size: 64
  rw_options:
    modality: Load # in [Create, CreateAndSave, Load]
    dirpath: ../tokenized_datasets/default_save_dir/ 
    light: True
  

logger:
  project : cancellami
  entity : NooneBug
  name : box_embedding_baseline_bbn
  config_file: auto