seed_everything : 3

trainer:
  deterministic: True
  gpus: 1
  limit_train_batches: 160
  max_epochs : 100
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: trained_models/bbn/
        monitor: val_loss
        filename: model_ckpt_name
        save_weights_only: True
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 5
        monitor: val_loss
        mode: min
        verbose: True